### ISSUE TITLE
Exported image is nested in several folders

### ISSUE THREAD

**Issue by mplorentz** [kocheck/Lazy-Export#33]
Not sure if this is a bug or a side-effect of how the Figma document was organized but when I exported an image today it came nested in several folders. PM me for a link to the figma frame.
![Screen Shot 2020-07-30 at 2 08 12 PM](https://user-images.githubusercontent.com/1165004/88958184-1c39b180-d26e-11ea-9700-ba44d03d43fc.png)

**Comment by kocheck** [comment]
@mplorentz  I think that could be how that icon was named. Could you send me a link when able So I can try to reproduce?
