### ISSUE TITLE
Set Custom presets

### ISSUE THREAD

**Issue by rivadav** [kocheck/Lazy-Export#37]
Hey,

I often have to export assets at a few sizes which iOS and Android presets don't cover (like 1.25x). It'd save me a ton of repetitive work when I could set the multipliers once and apply it later to different assets. Even if it would remember my settings only on a local machine, it'd be a great time-saver :)

**Comment by kocheck** [comment]
@rivadav Thanks for posting this! I am working on this actively again and appreciate your feedback! I will add this in Thank you!
